language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libnotmuch-dev
    - notmuch
    - git

script:
  - cargo build --no-default-features --verbose --all
  # clone notmuch to have mail corpora
  - git clone git://git.notmuchmail.org/git/notmuch
  - cargo test --no-default-features --verbose --all
